import type { ConsoleAccount, ConsoleGroup } from "./access";

/** Built-in roles that ship with HQ and cannot be deleted. */
export const DEFAULT_TENANT_GROUP_IDS = [
  "g-admin",
  "g-store-manager",
  "g-accountant",
  "g-sales",
  "g-cashier",
  "g-inventory",
  "g-support",
] as const;

export const DEFAULT_PRODUCER_GROUP_IDS = [
  "g-super-admin",
  "g-ceo",
  "g-ops",
  "g-prod-finance",
  "g-people",
  "g-product",
  "g-prod-sales",
  "g-prod-support",
] as const;

export const DEFAULT_GROUP_IDS = [
  ...DEFAULT_TENANT_GROUP_IDS,
  ...DEFAULT_PRODUCER_GROUP_IDS,
] as const;

export function isDefaultGroupId(id: string) {
  return (DEFAULT_GROUP_IDS as readonly string[]).includes(id);
}

export function isProducerGroupId(id: string) {
  return (DEFAULT_PRODUCER_GROUP_IDS as readonly string[]).includes(id);
}

export const SEED_PRODUCER_GROUPS: ConsoleGroup[] = [
  {
    id: "g-super-admin",
    name: "Super Admin",
    scope: "producer",
    departments: ["*"],
    privileges: ["*"],
  },
  {
    id: "g-ceo",
    name: "CEO",
    scope: "producer",
    departments: ["Main", "Business", "Billing", "People", "Analytics", "Admin"],
    privileges: [
      "super-home",
      "super-activity",
      "super-notifications",
      "super-companies",
      "super-branches",
      "super-stores",
      "super-storefronts",
      "super-tills",
      "super-billing-subscriptions",
      "super-billing-plans",
      "super-people-owners",
      "super-people-access",
      "super-analytics",
      "super-admins",
      "super-admin-roles",
      "super-account",
    ],
  },
  {
    id: "g-ops",
    name: "Operations",
    scope: "producer",
    departments: ["Main", "Business"],
    privileges: [
      "super-home",
      "super-companies",
      "super-branches",
      "super-stores",
      "super-storefronts",
      "super-tills",
    ],
  },
  {
    id: "g-prod-finance",
    name: "Finance",
    scope: "producer",
    departments: ["Main", "Billing", "Commerce"],
    privileges: [
      "super-home",
      "super-billing-plans",
      "super-billing-subscriptions",
      "super-billing-invoices",
      "super-billing-payments",
      "super-billing-usage",
      "super-commerce-gateways",
    ],
  },
  {
    id: "g-people",
    name: "People",
    scope: "producer",
    departments: ["Main", "People", "Admin"],
    privileges: [
      "super-home",
      "super-people-users",
      "super-people-owners",
      "super-people-staff",
      "super-people-roles",
      "super-people-access",
      "super-admins",
      "super-admin-roles",
    ],
  },
  {
    id: "g-product",
    name: "Product",
    scope: "producer",
    departments: ["Main", "Business", "Catalog"],
    privileges: [
      "super-home",
      "super-stores",
      "super-tills",
      "super-catalog-products",
      "super-catalog-inventory",
    ],
  },
  {
    id: "g-prod-sales",
    name: "Sales & Partnerships",
    scope: "producer",
    departments: ["Main", "Business"],
    privileges: ["super-home", "super-companies"],
  },
  {
    id: "g-prod-support",
    name: "Support",
    scope: "producer",
    departments: ["Main", "Support"],
    privileges: [
      "super-home",
      "super-support",
      "super-support-tickets",
      "super-support-requests",
    ],
  },
];

/** Seven real HQ roles with sidebar-aligned privileges. */
export const SEED_GROUPS: ConsoleGroup[] = [
  {
    id: "g-admin",
    name: "Administrator",
    scope: "tenant",
    departments: ["*"],
    privileges: ["*"],
  },
  {
    id: "g-store-manager",
    name: "Store Manager",
    departments: ["Report", "Setup"],
    privileges: [
      "dashboard",
      "items",
      "sales",
      "pos-hub",
      "sales-gp-subgroup",
      "purchase-order",
      "sales-return-list",
      "stock-report",
      "sales-invoice-list",
      "payments",
      "audit",
      "customer",
      "vendor",
      "staff",
      "sales-rep",
      "payment-method",
      "sales-promotion",
      "chat",
      "help",
    ],
  },
  {
    id: "g-accountant",
    name: "Accountant",
    departments: ["Report", "Setup"],
    privileges: [
      "dashboard",
      "sales",
      "stock-report",
      "sales-invoice-list",
      "payments",
      "audit",
      "finance",
      "accounting-books",
      "accounting-statements",
      "balance",
      "ledger",
      "trail",
      "tax",
      "expense-account",
      "billing",
      "help",
    ],
  },
  {
    id: "g-sales",
    name: "Sales Associate",
    departments: ["Report", "Setup"],
    privileges: [
      "pos-hub",
      "payments",
      "sales-return-list",
      "sales-invoice-list",
      "customer",
      "sales-rep",
      "sales-promotion",
      "chat",
      "help",
    ],
  },
  {
    id: "g-cashier",
    name: "Cashier",
    departments: ["Report", "Setup"],
    privileges: ["pos-hub", "payments", "sales-return-list", "customer", "help"],
  },
  {
    id: "g-inventory",
    name: "Inventory Clerk",
    departments: ["Report", "Setup"],
    privileges: ["items", "stock-report", "purchase-order", "vendor", "payments", "help"],
  },
  {
    id: "g-support",
    name: "Support Agent",
    departments: ["Setup"],
    privileges: ["chat", "support", "customer", "help"],
  },
];

export const SEED_ACCOUNTS: ConsoleAccount[] = [
  {
    id: "a-emma",
    name: "Emma Wang",
    email: "emma.wang@example.com",
    username: "emma",
    password: "demo",
    groupId: "g-admin",
    active: true,
  },
  {
    id: "a-funke",
    name: "Funke Adeyemi",
    email: "funke.adeyemi@example.com",
    username: "funke",
    password: "demo",
    groupId: "g-store-manager",
    active: true,
  },
  {
    id: "a-chika",
    name: "Chika Okonkwo",
    email: "chika.okonkwo@example.com",
    username: "chika",
    password: "demo",
    groupId: "g-accountant",
    active: true,
  },
  {
    id: "a-tosin",
    name: "Tosin Adeyemi",
    email: "tosin.adeyemi@example.com",
    username: "tosin",
    password: "demo",
    groupId: "g-sales",
    active: true,
  },
  {
    id: "a-amaka",
    name: "Amaka Eze",
    email: "amaka.eze@example.com",
    username: "amaka",
    password: "demo",
    groupId: "g-cashier",
    active: true,
  },
  {
    id: "a-ibrahim",
    name: "Ibrahim Bello",
    email: "ibrahim.bello@example.com",
    username: "ibrahim",
    password: "demo",
    groupId: "g-inventory",
    active: true,
  },
  {
    id: "a-david",
    name: "David Okoro",
    email: "david.okoro@example.com",
    username: "david",
    password: "demo",
    groupId: "g-support",
    active: true,
  },
];
