export type CatalogItem = {
  id: string;
  name: string;
  category: string;
  subcategory?: string;
  sku: string;
  barcode: string;
  batchNumber?: string;
  brand?: string;
  costMinor: number;
  priceMinor: number;
  currency: "NGN";
  image: string;
  onHand: number;
  reorderLevel: number;
  unit: string;
  unitLabel?: string;
  packSize: number;
  description?: string;
  active: boolean;
  updatedAt: string;
  expiresAt?: string;
};