import type { PolicyKind } from "@/lib/hq-policies";
import type { PolicyColumn, PolicyField } from "./PolicyManager";

export type PolicyConfig = {
  kind: PolicyKind;
  group: string;
  label: string;
  copy: string;
  kicker: string;
  title: string;
  columns: PolicyColumn[];
  fields: PolicyField[];
  blank: Record<string, string | boolean>;
};

const activeBadge = (value: string) => (value.toLowerCase() === "yes" ? "emerald" : "slate");

export const POLICY_CONFIGS: PolicyConfig[] = [
  {
    kind: "businesses",
    group: "Business",
    label: "Add Business",
    copy: "Additional businesses you operate beyond the default company profile.",
    kicker: "Settings · Business",
    title: "Add Business",
    columns: [
      { key: "name", label: "Business" },
      { key: "type", label: "Type", badge: true },
      { key: "registrationNumber", label: "Reg. number" },
      { key: "active", label: "Status", badge: true, render: (row) => (row.active === false ? "Paused" : "Active"), tone: activeBadge },
    ],
    fields: [
      { key: "name", label: "Business name", placeholder: "e.g. Simplebks Wholesale" },
      { key: "type", label: "Type", kind: "select", options: ["Store", "Wholesale", "Warehouse", "Kitchen", "Service"] },
      { key: "registrationNumber", label: "Registration number", placeholder: "e.g. RC 1234567" },
      { key: "address", label: "Address", placeholder: "Registered address" },
      { key: "city", label: "City", placeholder: "e.g. Ikeja" },
      { key: "phone", label: "Phone", placeholder: "e.g. 0801 234 5678" },
      { key: "active", label: "Active", kind: "toggle", hint: "Enabled businesses appear in reports and setup pickers." },
    ],
    blank: { name: "", type: "Store", registrationNumber: "", address: "", city: "", phone: "", active: true },
  },
  {
    kind: "roles",
    group: "People",
    label: "Roles",
    copy: "Access roles your team members hold — each maps to a department and privilege level.",
    kicker: "Settings · People",
    title: "Roles",
    columns: [
      { key: "name", label: "Role" },
      { key: "department", label: "Department", badge: true },
      { key: "level", label: "Access", badge: true },
      { key: "active", label: "Status", badge: true, render: (row) => (row.active === false ? "Inactive" : "Active"), tone: activeBadge },
    ],
    fields: [
      { key: "name", label: "Role name", placeholder: "e.g. Shift Supervisor" },
      { key: "department", label: "Department", kind: "select", options: ["Office", "Counter", "Bakery", "Kitchen", "Store", "Dispatch"] },
      { key: "level", label: "Access level", kind: "select", options: ["Owner", "Manager", "Supervisor", "Staff"] },
      { key: "description", label: "Description", kind: "textarea", placeholder: "What this role is allowed to do." },
      { key: "active", label: "Active", kind: "toggle" },
    ],
    blank: { name: "", department: "Counter", level: "Staff", description: "", active: true },
  },
  {
    kind: "bankAccounts",
    group: "Money",
    label: "Bank Accounts",
    copy: "Bank accounts money moves through — tenders, advances and reconciliations reference these.",
    kicker: "Settings · Money",
    title: "Bank Accounts",
    columns: [
      { key: "name", label: "Account" },
      { key: "bank", label: "Bank", badge: true },
      { key: "accountNumber", label: "Number" },
      { key: "currency", label: "Currency" },
      { key: "isDefault", label: "Default", badge: true, render: (row) => (row.isDefault ? "Default" : "—"), tone: () => "emerald" },
      { key: "active", label: "Status", badge: true, render: (row) => (row.active === false ? "Inactive" : "Active"), tone: activeBadge },
    ],
    fields: [
      { key: "name", label: "Account name", placeholder: "e.g. Main operating account" },
      { key: "bank", label: "Bank", placeholder: "e.g. Access Bank" },
      { key: "accountNumber", label: "Account number", placeholder: "10-digit number" },
      { key: "accountName", label: "Beneficiary name", placeholder: "Name on the account" },
      { key: "currency", label: "Currency", kind: "select", options: ["NGN", "USD", "GHS", "KES"] },
      { key: "isDefault", label: "Default account", kind: "toggle" },
      { key: "active", label: "Active", kind: "toggle" },
    ],
    blank: { name: "", bank: "", accountNumber: "", accountName: "", currency: "NGN", isDefault: false, active: true },
  },
  {
    kind: "expenseControls",
    group: "Money",
    label: "Expense Controls",
    copy: "Approval levels and limits for team spending — who can book what without a manager sign-off.",
    kicker: "Settings · Money",
    title: "Expense Controls",
    columns: [
      { key: "name", label: "Rule" },
      { key: "approvalThresholdMinor", label: "Approval above", render: (row) => `₦${Number(row.approvalThresholdMinor ?? 0).toLocaleString()}` },
      { key: "role", label: "Approver role", badge: true },
      { key: "receiptsRequired", label: "Receipts", badge: true, render: (row) => (row.receiptsRequired === false ? "Optional" : "Required"), tone: () => "emerald" },
      { key: "active", label: "Status", badge: true, render: (row) => (row.active === false ? "Off" : "On"), tone: activeBadge },
    ],
    fields: [
      { key: "name", label: "Rule name", placeholder: "e.g. Standard expenses" },
      { key: "approvalThresholdMinor", label: "Require approval above (₦)", kind: "number", placeholder: "e.g. 50000" },
      { key: "role", label: "Approver role", kind: "select", options: ["Owner", "Manager", "Supervisor"] },
      { key: "receiptsRequired", label: "Receipts required", kind: "toggle" },
      { key: "allowReceiptless", label: "Allow receiptless below threshold", kind: "toggle" },
      { key: "active", label: "Active", kind: "toggle" },
    ],
    blank: { name: "", approvalThresholdMinor: "0", role: "Manager", receiptsRequired: true, allowReceiptless: true, active: true },
  },
  {
    kind: "reconciliations",
    group: "Money",
    label: "Reconciliation",
    copy: "Matching rules for cash and bank reconciliations — tolerance, VAT treatment and default mode.",
    kicker: "Settings · Money",
    title: "Reconciliation",
    columns: [
      { key: "name", label: "Rule" },
      { key: "toleranceMinor", label: "Tolerance", render: (row) => `₦${Number(row.toleranceMinor ?? 0).toLocaleString()}` },
      { key: "vatTreatment", label: "VAT", badge: true },
      { key: "mode", label: "Mode", badge: true },
      { key: "active", label: "Status", badge: true, render: (row) => (row.active === false ? "Off" : "On"), tone: activeBadge },
    ],
    fields: [
      { key: "name", label: "Rule name", placeholder: "e.g. Till vs bank" },
      { key: "toleranceMinor", label: "Tolerance (₦)", kind: "number", placeholder: "e.g. 500" },
      { key: "vatTreatment", label: "VAT treatment", kind: "select", options: ["Exclusive", "Inclusive", "Split"] },
      { key: "mode", label: "Mode", kind: "select", options: ["Automatic", "Suggested", "Manual"] },
      { key: "active", label: "Active", kind: "toggle" },
    ],
    blank: { name: "", toleranceMinor: "0", vatTreatment: "Inclusive", mode: "Suggested", active: true },
  },
  {
    kind: "assetDefaults",
    group: "Money",
    label: "Fixed Assets",
    copy: "Default asset categories and useful life assumptions that new fixed assets inherit.",
    kicker: "Settings · Money",
    title: "Fixed Assets",
    columns: [
      { key: "name", label: "Category" },
      { key: "lifeYears", label: "Useful life", render: (row) => `${row.lifeYears ?? 5} yr` },
      { key: "salvagePct", label: "Salvage", render: (row) => `${row.salvagePct ?? 0}%` },
      { key: "depreciation", label: "Method", badge: true },
      { key: "active", label: "Status", badge: true, render: (row) => (row.active === false ? "Inactive" : "Active"), tone: activeBadge },
    ],
    fields: [
      { key: "name", label: "Category", placeholder: "e.g. Computer equipment" },
      { key: "lifeYears", label: "Useful life (years)", kind: "number", placeholder: "e.g. 4" },
      { key: "salvagePct", label: "Salvage value %", kind: "number", placeholder: "e.g. 10" },
      { key: "depreciation", label: "Method", kind: "select", options: ["Straight-line", "Declining balance"] },
      { key: "active", label: "Active", kind: "toggle" },
    ],
    blank: { name: "", lifeYears: "5", salvagePct: "0", depreciation: "Straight-line", active: true },
  },
  {
    kind: "productionPolicies",
    group: "Operations",
    label: "Production policy",
    copy: "How production runs are approved — budget tolerance, scrap reasons and batch approval style.",
    kicker: "Settings · Operations",
    title: "Production Policy",
    columns: [
      { key: "name", label: "Policy" },
      { key: "approvalStyle", label: "Approval", badge: true },
      { key: "budgetTolerancePct", label: "Budget tolerance", render: (row) => `${row.budgetTolerancePct ?? 5}%` },
      { key: "scrapReasons", label: "Scrap reasons" },
      { key: "active", label: "Status", badge: true, render: (row) => (row.active === false ? "Off" : "On"), tone: activeBadge },
    ],
    fields: [
      { key: "name", label: "Policy name", placeholder: "e.g. Bakery batches" },
      { key: "approvalStyle", label: "Approval style", kind: "select", options: ["None", "Manager", "Owner"] },
      { key: "budgetTolerancePct", label: "Budget tolerance %", kind: "number", placeholder: "e.g. 5" },
      { key: "scrapReasons", label: "Scrap reasons", kind: "textarea", placeholder: "Comma-separated, e.g. Overbake, Spilled, Expired dough" },
      { key: "active", label: "Active", kind: "toggle" },
    ],
    blank: { name: "", approvalStyle: "Manager", budgetTolerancePct: "5", scrapReasons: "Overbake, Spilled, Expired dough", active: true },
  },
  {
    kind: "stockPolicies",
    group: "Operations",
    label: "Sales & Stock Policies",
    copy: "Default selling and stock rules — negative stock, low-stock thresholds and price overrides.",
    kicker: "Settings · Operations",
    title: "Sales & Stock Policies",
    columns: [
      { key: "name", label: "Policy" },
      { key: "allowNegativeStock", label: "Negative stock", badge: true, render: (row) => (row.allowNegativeStock === false ? "Blocked" : "Allowed"), tone: (v) => (v === "Blocked" ? "rose" : "emerald") },
      { key: "lowStockThreshold", label: "Low-stock", render: (row) => String(row.lowStockThreshold ?? 5) },
      { key: "priceOverride", label: "Price override", badge: true, render: (row) => (row.priceOverride === false ? "Locked" : "Allowed"), tone: () => "emerald" },
      { key: "active", label: "Status", badge: true, render: (row) => (row.active === false ? "Off" : "On"), tone: activeBadge },
    ],
    fields: [
      { key: "name", label: "Policy name", placeholder: "e.g. Default selling rules" },
      { key: "allowNegativeStock", label: "Allow negative stock", kind: "toggle" },
      { key: "lowStockThreshold", label: "Low-stock threshold", kind: "number", placeholder: "e.g. 5" },
      { key: "priceOverride", label: "Allow price override at till", kind: "toggle" },
      { key: "maxDiscountPct", label: "Max discount %", kind: "number", placeholder: "e.g. 10" },
      { key: "active", label: "Active", kind: "toggle" },
    ],
    blank: { name: "", allowNegativeStock: false, lowStockThreshold: "5", priceOverride: true, maxDiscountPct: "10", active: true },
  },
  {
    kind: "approvals",
    group: "Operations",
    label: "Awaiting Approval",
    copy: "Items sitting in the approval queue — mark them approved or rejected as you work through them.",
    kicker: "Settings · Operations",
    title: "Awaiting Approval",
    columns: [
      { key: "entity", label: "Item" },
      { key: "type", label: "Type", badge: true },
      { key: "amountMinor", label: "Amount", render: (row) => `₦${Number(row.amountMinor ?? 0).toLocaleString()}` },
      { key: "requestedBy", label: "Requested by" },
      { key: "status", label: "Status", badge: true, tone: (v) => (v === "Approved" ? "emerald" : v === "Rejected" ? "rose" : "slate") },
    ],
    fields: [
      { key: "entity", label: "Item / reference", placeholder: "e.g. POS #1042" },
      { key: "type", label: "Type", kind: "select", options: ["Refund", "Discount", "Expense", "Purchase order", "Price override"] },
      { key: "amountMinor", label: "Amount (₦)", kind: "number", placeholder: "e.g. 5000" },
      { key: "requestedBy", label: "Requested by", placeholder: "e.g. Chika Okonkwo" },
      { key: "status", label: "Status", kind: "select", options: ["Pending", "Approved", "Rejected"] },
    ],
    blank: { entity: "", type: "Expense", amountMinor: "0", requestedBy: "", status: "Pending" },
  },
  {
    kind: "integrations",
    group: "Operations",
    label: "Integrations & Web Sync",
    copy: "External integrations and web sync hooks — toggle them and track the last successful sync.",
    kicker: "Settings · Operations",
    title: "Integrations & Web Sync",
    columns: [
      { key: "name", label: "Integration" },
      { key: "provider", label: "Provider", badge: true },
      { key: "lastSyncedAt", label: "Last sync", render: (row) => String(row.lastSyncedAt ?? "—") },
      { key: "enabled", label: "Status", badge: true, render: (row) => (row.enabled === false ? "Disabled" : "Enabled"), tone: (v) => (v === "Enabled" ? "emerald" : "slate") },
    ],
    fields: [
      { key: "name", label: "Integration name", placeholder: "e.g. QuickBooks sync" },
      { key: "provider", label: "Provider", kind: "select", options: ["QuickBooks", "Xero", "WooCommerce", "Shopify", "Webhook", "Google Sheets"] },
      { key: "endpoint", label: "Webhook / endpoint", placeholder: "https://…" },
      { key: "lastSyncedAt", label: "Last synced", kind: "date" },
      { key: "enabled", label: "Enabled", kind: "toggle" },
    ],
    blank: { name: "", provider: "Webhook", endpoint: "", lastSyncedAt: "", enabled: true },
  },
  {
    kind: "notificationChannels",
    group: "Notifications",
    label: "Notifications",
    copy: "Where notifications are delivered — pick channels and the events each one receives.",
    kicker: "Settings · Notifications",
    title: "Notifications",
    columns: [
      { key: "name", label: "Channel" },
      { key: "channel", label: "Type", badge: true },
      { key: "events", label: "Events", render: (row) => String(row.events ?? "") },
      { key: "active", label: "Status", badge: true, render: (row) => (row.active === false ? "Off" : "On"), tone: activeBadge },
    ],
    fields: [
      { key: "name", label: "Channel label", placeholder: "e.g. Owner phone" },
      { key: "channel", label: "Type", kind: "select", options: ["Email", "SMS", "Push", "In-app"] },
      { key: "recipient", label: "Recipient", placeholder: "e.g. owner@simplebks.com" },
      { key: "events", label: "Events", kind: "textarea", placeholder: "Comma-separated, e.g. Low stock, New sale, Shift close" },
      { key: "active", label: "Active", kind: "toggle" },
    ],
    blank: { name: "", channel: "Email", recipient: "", events: "Low stock, New sale, Shift close", active: true },
  },
  {
    kind: "notificationHistory",
    group: "Notifications",
    label: "Notification History",
    copy: "Recent notification deliveries and their outcome — a record of what was sent and whether it landed.",
    kicker: "Settings · Notifications",
    title: "Notification History",
    columns: [
      { key: "subject", label: "Subject" },
      { key: "channel", label: "Channel", badge: true },
      { key: "recipient", label: "Recipient" },
      { key: "status", label: "Status", badge: true, tone: (v) => (v === "Sent" ? "emerald" : v === "Failed" ? "rose" : "slate") },
      { key: "sentAt", label: "Sent", render: (row) => String(row.sentAt ?? "—") },
    ],
    fields: [
      { key: "subject", label: "Subject", placeholder: "e.g. Daily sales summary" },
      { key: "channel", label: "Channel", kind: "select", options: ["Email", "SMS", "Push", "In-app"] },
      { key: "recipient", label: "Recipient", placeholder: "e.g. owner@simplebks.com" },
      { key: "status", label: "Status", kind: "select", options: ["Sent", "Queued", "Failed"] },
      { key: "sentAt", label: "Sent at", kind: "date" },
    ],
    blank: { subject: "", channel: "Email", recipient: "", status: "Sent", sentAt: "" },
  },
  {
    kind: "archives",
    group: "Administration & Data",
    label: "Archives",
    copy: "Records you've archived from the working files — kept for reference without cluttering active lists.",
    kicker: "Settings · Administration & Data",
    title: "Archives",
    columns: [
      { key: "name", label: "Item" },
      { key: "kind", label: "Kind", badge: true },
      { key: "reason", label: "Reason" },
      { key: "archivedAt", label: "Archived", render: (row) => String(row.archivedAt ?? "—") },
    ],
    fields: [
      { key: "name", label: "Item name", placeholder: "e.g. Customer — Jane Doe" },
      { key: "kind", label: "Kind", kind: "select", options: ["Customer", "Vendor", "Item", "Till", "Template"] },
      { key: "reason", label: "Reason", kind: "textarea", placeholder: "Why it was archived." },
      { key: "archivedAt", label: "Archived at", kind: "date" },
    ],
    blank: { name: "", kind: "Customer", reason: "", archivedAt: "" },
  },
  {
    kind: "offlineSyncs",
    group: "Administration & Data",
    label: "Offline Sync",
    copy: "Devices that work offline and sync later — track pending data and the last time each till synced.",
    kicker: "Settings · Administration & Data",
    title: "Offline Sync",
    columns: [
      { key: "name", label: "Device" },
      { key: "store", label: "Store", badge: true },
      { key: "pending", label: "Pending", badge: true, render: (row) => (row.pending ? "Yes" : "Clear"), tone: (v) => (v === "Clear" ? "emerald" : "rose") },
      { key: "lastSyncedAt", label: "Last synced", render: (row) => String(row.lastSyncedAt ?? "—") },
    ],
    fields: [
      { key: "name", label: "Device", placeholder: "e.g. Back-office till" },
      { key: "store", label: "Store", placeholder: "e.g. Lekki" },
      { key: "lastSyncedAt", label: "Last synced", kind: "date" },
      { key: "pending", label: "Has pending data", kind: "toggle" },
    ],
    blank: { name: "", store: "", lastSyncedAt: "", pending: false },
  },
  {
    kind: "bulkRuns",
    group: "Administration & Data",
    label: "Bulk Run Tracker",
    copy: "Bulk import/export runs — the row counts and status behind each batch operation.",
    kicker: "Settings · Administration & Data",
    title: "Bulk Run Tracker",
    columns: [
      { key: "name", label: "Run" },
      { key: "kind", label: "Kind", badge: true },
      { key: "rows", label: "Rows", render: (row) => String(row.rows ?? 0) },
      { key: "status", label: "Status", badge: true, tone: (v) => (v === "Completed" ? "emerald" : v === "Failed" ? "rose" : "slate") },
      { key: "startedAt", label: "Started", render: (row) => String(row.startedAt ?? "—") },
    ],
    fields: [
      { key: "name", label: "Run name", placeholder: "e.g. Christmas catalog import" },
      { key: "kind", label: "Kind", kind: "select", options: ["Import", "Export", "Backfill"] },
      { key: "rows", label: "Row count", kind: "number", placeholder: "e.g. 1200" },
      { key: "status", label: "Status", kind: "select", options: ["Queued", "Running", "Completed", "Failed"] },
      { key: "startedAt", label: "Started", kind: "date" },
    ],
    blank: { name: "", kind: "Import", rows: "0", status: "Queued", startedAt: "" },
  },
  {
    kind: "historicalSyncs",
    group: "Administration & Data",
    label: "Historical Sync & Backfill",
    copy: "Backfills that pull historical data into the system — from where and how far back each one reaches.",
    kicker: "Settings · Administration & Data",
    title: "Historical Sync & Backfill",
    columns: [
      { key: "name", label: "Backfill" },
      { key: "source", label: "Source", badge: true },
      { key: "fromDate", label: "From", render: (row) => String(row.fromDate ?? "—") },
      { key: "status", label: "Status", badge: true, tone: (v) => (v === "Completed" ? "emerald" : v === "Failed" ? "rose" : "slate") },
    ],
    fields: [
      { key: "name", label: "Backfill name", placeholder: "e.g. 2025 sales history" },
      { key: "source", label: "Source", kind: "select", options: ["Legacy till", "Spreadsheet", "Previous system"] },
      { key: "fromDate", label: "Backfill from", kind: "date" },
      { key: "status", label: "Status", kind: "select", options: ["Queued", "Running", "Completed", "Failed"] },
    ],
    blank: { name: "", source: "Legacy till", fromDate: "", status: "Queued" },
  },
  {
    kind: "sharedDevices",
    group: "Administration & Data",
    label: "Shared Devices",
    copy: "POS devices that are shared between operators — device security and PIN requirements.",
    kicker: "Settings · Administration & Data",
    title: "Shared Devices",
    columns: [
      { key: "name", label: "Device" },
      { key: "store", label: "Store", badge: true },
      { key: "requirePin", label: "PIN", badge: true, render: (row) => (row.requirePin ? "Required" : "None"), tone: (v) => (v === "Required" ? "emerald" : "slate") },
      { key: "active", label: "Status", badge: true, render: (row) => (row.active === false ? "Blocked" : "Active"), tone: activeBadge },
    ],
    fields: [
      { key: "name", label: "Device name", placeholder: "e.g. Counter till 2" },
      { key: "store", label: "Store", placeholder: "e.g. Surulere" },
      { key: "requirePin", label: "Require operator PIN", kind: "toggle" },
      { key: "active", label: "Active", kind: "toggle" },
    ],
    blank: { name: "", store: "", requirePin: true, active: true },
  },
  {
    kind: "accountData",
    group: "Administration & Data",
    label: "Account & Data",
    copy: "Account-level data actions — cutover, reset and close-out records for this workspace.",
    kicker: "Settings · Administration & Data",
    title: "Account & Data",
    columns: [
      { key: "name", label: "Action" },
      { key: "kind", label: "Type", badge: true },
      { key: "status", label: "Status", badge: true, tone: (v) => (v === "Completed" ? "emerald" : v === "Pending" ? "rose" : "slate") },
      { key: "note", label: "Note" },
    ],
    fields: [
      { key: "name", label: "Action label", placeholder: "e.g. Cutover to new company" },
      { key: "kind", label: "Type", kind: "select", options: ["Cutover", "Reset", "Close account", "Merge"] },
      { key: "status", label: "Status", kind: "select", options: ["Pending", "Completed", "Scheduled"] },
      { key: "note", label: "Note", kind: "textarea", placeholder: "Details of the action." },
    ],
    blank: { name: "", kind: "Cutover", status: "Pending", note: "" },
  },
];

export type ExistingLink = {
  label: string;
  copy: string;
  href: string;
  group: string;
};

export const EXISTING_LINKS: ExistingLink[] = [
  { group: "Business", label: "Business Profile", copy: "Company identity, registration and contact details.", href: "/setup/others/company" },
  { group: "Business", label: "Locations", copy: "Branches, stores and storefronts you operate.", href: "/setup/others/branch" },
  { group: "People", label: "Team", copy: "Staff directory, departments and roster status.", href: "/setup/staff" },
  { group: "Money", label: "Billing", copy: "Subscriptions, till licences and invoices.", href: "/setup/billing/subscriptions" },
  { group: "Money", label: "Plan", copy: "Your current subscription plan.", href: "/setup/billing/subscriptions" },
  { group: "Money", label: "Tax Compliance", copy: "Tax types, rates and registration numbers.", href: "/setup/others/tax" },
  { group: "Operations", label: "Receipts & Documents", copy: "Receipt template, header and footer.", href: "/setup/others/settings?section=receipts" },
  { group: "Operations", label: "Invoice Customization", copy: "Invoice template, prefix and branding.", href: "/setup/others/settings?section=invoices" },
  { group: "Operations", label: "Units of Measure", copy: "Count, weight, volume and pack units.", href: "/setup/items/units" },
  { group: "Operations", label: "Promotions & Loyalty", copy: "Discount campaigns and loyalty programme.", href: "/setup/sales-promotion" },
  { group: "Administration & Data", label: "Data Export", copy: "Export your data for backup or migration.", href: "/setup/others/export" },
  { group: "My account", label: "Profile & Security", copy: "Your sign-in details, PIN and security options.", href: "/setup/users/account" },
];